### PR TITLE
#22

### PR DESCRIPTION
**Pull request by thomasmodeneis**

### CODE REVIEW

**Comment by neomatrix369** [comment]
@thomasmodeneis - branch is not in sync with master, otherwise its good to merge, I trust the translations are in par with the English version.

**Comment by thomasmodeneis** [comment]
yes I'm trying to sync the branch and make this work.

**Comment by neomatrix369** [comment]
@thomasmodeneis any progress with this pull request ?

**Comment by thomasmodeneis** [comment]
all ready for the merge, sorry for the delay.

**Comment by neomatrix369** [comment]
@thomasmodeneis any progress with this PR or should it be closed ?

**Comment by thomasmodeneis** [comment]
I left the merge to be completed by yourself sir, but I just did it.

**Pull request merged**
