### PR TITLE
Simple explanations

### PR DESCRIPTION
**Pull request by mohanr**
I have added some simple one line explanations wherever I thought it made sense.

### CODE REVIEW

**Comment by neomatrix369** [comment]
@mohanr good work, an improvement over the first commits. Can you please add some explanations in lay person's terms as well, the current comments may be perceived a bit technical (graphic terminologies)  by some. 

Just things like what do the min, avg and max mean - which one is good and which isn't and why are they good. Maybe even expand on how could performance be improved - things like that. Or if you think, there can be no more improvements.

Take your time to prepare this - its useful stuff you have put together. - Thanks mate.

**Comment by mohanr** [comment]
I was thinking about adding more about the statistical measures but thought
they don't belong in a Java book. Will add some more basic explanations.

Mohan

**Comment by neomatrix369** [comment]
Anything to explain the material under JMH will be a bonus and helpful for the readers. You could also provide links to external sites if these explanations are available there.

**Comment by neomatrix369** [comment]
@mohanr any progress with this pull request ?

**Comment by mohanr** [comment]
Nothing yet. But I will review this this weekend. I plan to add some more
basic definitions of the statistical interpretation of the JMH results.
Hope you meant that ?

Mohan

**Comment by mohanr** [comment]
Hi Mani,
                  Could you disapprove that pull request ? I will submit
one when I have more information.

Thanks,
Mohan

**Comment by neomatrix369** [comment]
@mohanr PR has been closed on your request

**Pull request closed without merging**
