### PR TITLE
Incorporating the quick-start guide

### PR DESCRIPTION
**Pull request by allandequeiroz**
To keep users inside the book I've removed the external quick-start guide link and brought the content to the book.

Thinking about the possibility of people feel like trying something even before start reading the book, I put it just before **How to navigate and make progress?**.

screen shot 2017-05-21 at 09 20 21

* I also removed the redundant link from the main page to avoid people getting out of it.

### CODE REVIEW

**Comment by neomatrix369** [comment]
This is really great work.
@mikebgx do you mind taking a look at it to see if your work is preserved after @allandequeiroz blended it into the main book? Thanks.

**Comment by neomatrix369** [comment]
@allandequeiroz you might need to run the `whatsChanged.sh` script for all languages

**Comment by mikebgx** [comment]
Great work indeed, I had been meaning to do it for a while, many thanks Alan. 

Yes I'll take a look, in a few days, snowed under at present. 

Best Regards

Mike Burton
(Sent from my iPhone)

**Comment by allandequeiroz** [comment]
Thanks for that @neomatrix369 and @mikebgx. 

I just updated the what's changed for all languages.

Thanks guys.

**Comment by mikebgx** [comment]
I checked and it all looks great, nice work!

**Comment by allandequeiroz** [comment]
Thanks @mikebgx !

**Comment by neomatrix369** [comment]
@allandequeiroz Just before I merge it since it looks good, could you please see if there are any conceptual duplicates between the quick start guide you added and other parts of the GSK?

**Comment by allandequeiroz** [comment]
Absolutely @neomatrix369, as soon I get home I'll do that.

**Comment by allandequeiroz** [comment]
Hi guys ( @neomatrix369 @mikebgx  ), looks fine to me, the content is a good summarisation for those who are in a hurry to try something without navigating through the whole book.

Just one thing, maybe we could isolate it a little bit more removing the details link under "Start the VM" that take people elsewhere in the book.

The ones under "Next steps" make completely sense because the first three ones teach the person hack the JDK doing something concrete to deal with that curiosity of seen something real happening. Next ones drives to deeper understanding of surrounding topics.

So, to me looks quite good.

**Comment by neomatrix369** [comment]
Good work everyone, thanks all!

**Comment by neomatrix369** [comment]
Just one thing, maybe we could isolate it a little bit more removing the details link under "Start the VM" that take people elsewhere in the book. -- @allandequeiroz maybe create an issue and work on it separately and come back with a PR :+1:

**Pull request merged**
